index:  [/, src\Controller\BlogController.indexAction]
cart: [/cart/{id}, src\Controller\BlogController.cartAction]
upload: [/upload/{id}, src\Controller\BlogController.uploadAction]
page: [/page/{id}, src\Controller\BlogController.pageAction]
